import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/redux/ReduxProvider";
import LoginModal from "@/components/modals/loginModal/LoginModal";
import SignupModal from "@/components/modals/loginModal/SignupModal";
import ForgotPasswordModal from "@/components/modals/loginModal/ForgotPasswordModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          {children}
          <LoginModal />
          <SignupModal />
          <ForgotPasswordModal />
        </ReduxProvider>
      </body>
    </html>
  );
}
